### ISSUE TITLE
Thank you + improvement tip

### ISSUE THREAD

**Issue by johnykes** [fernando-mc/serverless-learn-serverlessjams#1]
Hi!
First of all, thank you for the youtube tutorial & this repository <3

 Maybe you should change "AUTH0_API_ID" to "AUTH0_API_AUDIENCE" (in severless.yml), because the audience is required, not the ID.

ps: I'm referring to 5.4

**Comment by fernando-mc** [comment]
Ahh, fair point. I've also thought about generalizing it more, because if you did this example with Cognito there might be equivalent values that are not Auth0. I'll see if I can change this in the repo/course at the same time, but that means I need to wait till I have some time to record... Probably a few weeks out for the change.

**Comment by johnykes** [comment]
do you know why the python import is not working? 
auth function can't import from get_token import get_token and from verify_token import verify_token
record_song_vote can't import from scope_check import scope_check

**Comment by fernando-mc** [comment]
Hi @johnykes I'm not sure why that would be happening, can you paste a screenshot of the errors and your configuration here so I can take a look?

**Comment by johnykes** [comment]
Something like "module not found", can't remember exactly. But it's okay, I merged all the auth0 functions in only one file and I'm checking right there if the scopes are okay for the called endpoint.

**Comment by fernando-mc** [comment]
Glad you got it working @johnykes!
